spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  sleuth:
    sampler:
      percentage: 0.5
  zipkin:
    baseUrl: http://localhost:9411/